homepage:
    controller: App\UseCase\Homepage\IndexAction
    path: /

thumbnail_serve:
    controller: App\UseCase\ServeResized\IndexAction
    path: /t/{checksum}/{strategy}/{size}/{format}/{id}
    methods: [ 'GET' ]
    requirements:
        id: '.+'

controllers:
    resource: ../src/Controller/
    type: attribute
