services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            array $supportedOutputFormats: [ 'jpeg', 'webp' ]

    # actions
    App\Controllers\:
        namespace: 'App\UseCase\'
        resource: '../src/UseCase/*/*Action.php'
        tags: [ { name: 'controller.service_arguments' } ]


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Core\Security\StringKeyVault:
        arguments: [ '%env(APP_SECRET_KEYS)%' ]

    App\Core\ResizeStrategy\ImmutableResizeStrategyFactory:
        arguments: [ {
            'fixed': '@App\Core\ResizeStrategy\ResizeStrategyFixed',
        } ]

    App\Core\Processor\ThumbnailProcessorInterface: '@App\Core\Processor\DefaultThumbnailProcessor'

    App\Core\Processor\CachingThumbnailProcessorDecorator:
        decorates: 'App\Core\Processor\ThumbnailProcessorInterface'
        arguments:
            $processor: '@.inner'
            $storage: '%env(APP_STORAGE_RESIZED)%'

    App\Core\Processor\LockingThumbnailProcessorDecorator:
        decorates: 'App\Core\Processor\ThumbnailProcessorInterface'
        arguments:
            $processor: '@.inner'

    App\Core\Source\ImageSourceInterface: '@App\Core\Source\AWSS3ImageSource'

    App\Core\Source\CachingImageSourceDecorator:
        decorates: 'App\Core\Source\ImageSourceInterface'
        arguments:
            $source: '@.inner'
            $storage: '%env(APP_STORAGE_SOURCES)%'

    App\Core\Source\AWSS3ImageSource:
        arguments:
            $s3Bucket: '%env(AWS_S3_BUCKET)%'

    Aws\S3\S3Client:
        arguments:
            - {
                region: '%env(AWS_S3_REGION)%',
                version: '%env(AWS_S3_VERSION)%',
                credentials: { key: '%env(AWS_S3_KEY)%', secret: '%env(AWS_S3_SECRET)%' }
            }

